spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:msl
    driver-class-name: org.h2.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update


    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

secret:
  key: "6e5162b6d720e12d29458c2d2977be26"

security:
  salt: maswillaengproject


logging:
  level:
    sql: debug