spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:MLS
    driver-class-name: org.h2.Driver
    username: root
    password: '0000'

  jpa:
    hibernate:
      ddl-auto: update

    generate-ddl: off

    properties:
      hibernate:
        format_sql: true

secret:
  access: access-test
  refresh: refresh-test

logging:
  level:
    sql: debug