spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

  jwt:
    secret: da7f3e46f4707ac128b0bc161c78ce832809dfba80084e0704f054099fb119a5155799d84b56c022087393512288699f0ee4b6d5391c34ae68a3c5828a120bda
