spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/msl
    driver-class-name: org.h2.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none

    generate-ddl: off

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: maswillaeng@gmail.com
    password: sxzrfipxjffamevp
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftlh

secret:
  access: mslbacksecretkeymslbacksecretkey

import:
  key: 5161304000601633
  secret: EZiN kyjk3eOAnikh95U24zgwsDcyzD4wYmuLr3WtnG1v9LkV1t3I3PYyIlp8TTCNNx7i9yd6Lw2JK5Ki


logging:
  level:
    sql: debug
