spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    jpa:
      defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    me.silvernine: DEBUG

secret:
  access: "f58244a11aea6530c36326f2dbba84ca27988c396e57b3bf71e9c4b459d5923baebd73aa97600e265c6e0b9f1aea6a70f0f6a06d2c75956f850dc68d8a5baa45"
  refresh: "06d0d40bfdcb3a9f296c6791f9b246ef8bb249cfc75e709e6aaab6ca0e427db143aaa099e95f5b92a3d890b40014c0574ff41ef051e5183e9ac00a7d28eda52b"