spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    h2:
      console:
        enabled: true

    hibernate:
      ddl-auto: validate

    open-in-view: true

    generate-ddl: off

    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    sql: debug